version: '3'

volumes:
  database-data:

services:
  database:
    image: postgres:14
    container_name: stock-database
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockinventory
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5433"
    shm_size: 1G

  app:
    container_name: stock-api
    build:
      context: ./backend
      dockerfile: ./dockerfiles/dev/Dockerfile
    environment:
      API_PORT: 4321
      ENVIRONMENT: development
      DATABASE_DRIVER: sql
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: stockinventory
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SSL_MODE: disable
      CONFIG_FILE_PATH: /var/lib/scripts/config.yml
    volumes:
      - ./backend:/var/lib/app
    working_dir: /var/lib/app
    ports:
      - "4321:4321"
    expose:
      - "4321"
    depends_on:
      - database
